; IOC Intelligence Platform -- Windows Installer
;
; Packages the existing Docker Compose-based platform (backend/, frontend/,
; docker-compose.yml, docker-compose.prod.yml) plus the PowerShell setup
; wizard and service-lifecycle scripts into a standard Windows installer.
;
; This does NOT reimplement the platform as a native Windows service --
; Docker Compose remains the real runtime. The installer's job is: copy
; files to Program Files, verify prerequisites (Docker Desktop, ports, disk),
; then hand off to Setup-Wizard.ps1 for real configuration and first start.
;
; Build with: "C:\Users\<you>\AppData\Local\Programs\Inno Setup 6\ISCC.exe" installer.iss
; (or wherever ISCC.exe is installed -- `winget list --id JRSoftware.InnoSetup`
; then locate it under %LocalAppData%\Programs if the top-level winget
; install path doesn't have it, which is the common case for a per-user
; winget install.)

#define MyAppName "HORIZON GRID"
#define MyAppVersion "0.2.5"
#define MyAppPublisher "HORIZON GRID"
#define MyAppURL "http://localhost:3000"
#define RepoRoot "..\"
; HORIZON GRID rebrand (visible strings only): MyAppName/MyAppPublisher above
; feed only the Setup.exe UI (title bar, dialogs, AppPublisher metadata) --
; deliberately NOT DefaultDirName/DefaultGroupName below. Common.ps1's
; $script:InstallDir/$script:AppRepoDir are computed from a hardcoded
; "IOC Intelligence Platform" folder name independent of anything in this
; .iss file, so if DefaultDirName followed MyAppName here, a fresh install
; would physically land under Program Files\HORIZON GRID while every
; installed PowerShell script would go on looking for its own files under
; Program Files\IOC Intelligence Platform -- breaking new installs, not just
; risking orphaning the one real existing install. MyAppFolderName keeps
; that on-disk name pinned regardless of MyAppName.
#define MyAppFolderName "IOC Intelligence Platform"

[Setup]
AppId={{B7E4A1C2-4F3D-4A8B-9C1E-1D2E3F4A5B6C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppSupportURL={#MyAppURL}
; Inno Setup does not auto-populate the compiled Setup.exe's own Win32
; FileVersion resource from AppVersion -- confirmed live via a real
; Get-Item(...).VersionInfo check showing ProductVersion correctly set but
; FileVersion blank. Cosmetic only (Explorer's File Version column), but
; free to fix.
VersionInfoVersion={#MyAppVersion}
DefaultDirName={autopf}\{#MyAppFolderName}
DefaultGroupName={#MyAppFolderName}
DisableProgramGroupPage=yes
; The wizard itself (Setup-Wizard.ps1) does the real configuration UI --
; Inno Setup's own pages just copy files and verify prerequisites, so this
; stays as a plain, minimal installer rather than duplicating pages.
PrivilegesRequired=admin
OutputDir=..\release
OutputBaseFilename=HORIZON-GRID-Setup-{#MyAppVersion}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
; No custom icon exists yet (windows\assets is empty) -- UninstallDisplayIcon
; is intentionally omitted rather than pointing at a fabricated file; Inno
; Setup falls back to its own default icon until a real one is added.
;
; Without this, {autopf} resolves to "Program Files (x86)" (Inno Setup
; compiles 32-bit by default) while Common.ps1's $env:ProgramFiles -- read
; from 64-bit PowerShell, since Docker Desktop and everything else on this
; platform is 64-bit-only -- resolves to the real "Program Files". That
; mismatch was caught live: a real test install landed in the x86 folder
; while every script the wizard runs afterward looks in the 64-bit one.
; Docker Desktop itself requires 64-bit Windows, so requiring x64 here
; costs nothing.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; The real application: backend/, frontend/, docker-compose*.yml, k8s/,
; docs/, README.md -- everything docker compose needs to build and run.
; .git, node_modules, __pycache__, and venvs are excluded since they're
; either irrelevant to a packaged install or get regenerated by npm
; install / pip install at image-build time inside the containers anyway.
; "nul" excluded: a stray file literally named "nul" (a reserved Windows
; device name) exists in backend\ from some earlier accidental `> nul`
; redirect -- Inno Setup's compressor can't read its file time and aborts
; the build on it. Not something this installer script should silently fix
; in the source tree; excluded here so packaging isn't blocked by it.
; "_qa_*.py,cleanup_qa_*.py" excluded: ad-hoc scratch/debug scripts created directly under
; backend\ during QA sessions (mint JWTs bypassing login, mutate runtime config with no
; actor attribution, delete users with no RBAC check) have no place in a shipping build --
; confirmed live that once one is transiently present in the dev tree at compile time, it
; gets baked into the installer permanently and reappears on every future install/reinstall
; even after being deleted from the dev tree, since Inno Setup's own uninstall log never
; tracked it as something IT installed in the first place.
; .venv/.venv_test are local dev-only virtualenvs used for running the test
; suite outside Docker -- the real app never runs from them (it builds fresh
; inside python:3.12-slim containers from requirements.txt on `docker compose
; up --build`). Found during a release-QA pass: without this exclusion, a
; 190MB+ local venv silently became the vast majority of every installer
; build's compressed content -- pure dead weight, never installed or run.
Source: "{#RepoRoot}backend\*"; DestDir: "{app}\app\backend"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: ".venv,.venv_test,__pycache__,*.pyc,.pytest_cache,celerybeat-schedule,nul,_qa_*.py,cleanup_qa_*.py,qa_halluc_out_*.json"
Source: "{#RepoRoot}frontend\*"; DestDir: "{app}\app\frontend"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "node_modules,.next,*.tsbuildinfo"
Source: "{#RepoRoot}docker-compose.yml"; DestDir: "{app}\app"; Flags: ignoreversion
Source: "{#RepoRoot}docker-compose.prod.yml"; DestDir: "{app}\app"; Flags: ignoreversion
Source: "{#RepoRoot}README.md"; DestDir: "{app}\app"; Flags: ignoreversion
Source: "{#RepoRoot}docs\*"; DestDir: "{app}\app\docs"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "scripts\*"; DestDir: "{app}\app\windows\scripts"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "wizard\*"; DestDir: "{app}\app\windows\wizard"; Flags: ignoreversion recursesubdirs createallsubdirs
; dontcopy: only extracted on demand via ExtractTemporaryFile in [Code], for
; the prerequisite check that runs on the Ready-to-Install page -- before
; the real [Files] copy (below) has necessarily finished, so this can't
; just read from {app}\app\windows\scripts yet.
Source: "scripts\Check-Prerequisites.ps1"; DestDir: "{tmp}"; Flags: dontcopy

[Icons]
Name: "{group}\Open Platform"; Filename: "powershell.exe"; Parameters: "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\app\windows\scripts\Open-Platform.ps1"""; WorkingDir: "{app}\app\windows\scripts"; Comment: "Start the platform if needed, wait until it's healthy, then open it in your browser"
Name: "{group}\Configuration"; Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\app\windows\wizard\Setup-Wizard.ps1"""; WorkingDir: "{app}\app\windows\wizard"; Comment: "Change AI backend, providers, ports, or the administrator account"
Name: "{group}\Start Platform"; Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\app\windows\scripts\Service-Start.ps1"""; WorkingDir: "{app}\app\windows\scripts"
Name: "{group}\Stop Platform"; Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\app\windows\scripts\Service-Stop.ps1"""; WorkingDir: "{app}\app\windows\scripts"
Name: "{group}\Restart Platform"; Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\app\windows\scripts\Service-Restart.ps1"""; WorkingDir: "{app}\app\windows\scripts"
Name: "{group}\Service Status"; Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\app\windows\scripts\Service-Status.ps1"""; WorkingDir: "{app}\app\windows\scripts"
Name: "{group}\Backup Database Now"; Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\app\windows\scripts\Backup-Database.ps1"""; WorkingDir: "{app}\app\windows\scripts"
Name: "{group}\Restore Database"; Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\app\windows\scripts\Restore-Database.ps1"""; WorkingDir: "{app}\app\windows\scripts"; Comment: "Replace the current database with a backup file -- destructive, asks for confirmation"
Name: "{group}\Diagnostics"; Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\app\windows\scripts\Diagnostics.ps1"""; WorkingDir: "{app}\app\windows\scripts"
Name: "{group}\Documentation"; Filename: "{app}\app\docs"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "powershell.exe"; Parameters: "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\app\windows\scripts\Open-Platform.ps1"""; WorkingDir: "{app}\app\windows\scripts"; Comment: "Start the platform if needed, wait until it's healthy, then open it in your browser"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut to the platform"; GroupDescription: "Additional shortcuts:"

[Run]
; Prerequisites are checked as a Code-driven step below (NextButtonClick),
; not here, because a failed hard check needs to stop the install with a
; real message box -- [Run]'s own error handling doesn't fit that flow.
Filename: "powershell.exe"; \
    Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\app\windows\wizard\Setup-Wizard.ps1"""; \
    WorkingDir: "{app}\app\windows\wizard"; \
    Description: "Launch the setup wizard now"; \
    Flags: postinstall nowait skipifsilent

[UninstallDelete]
; The uninstaller (Code section below) already prompts for Remove
; Application vs Remove Everything and handles ProgramData deletion itself
; when the administrator chooses the destructive option -- this only cleans
; up install-time artifacts Inno Setup's own [Files] section doesn't track.
Type: filesandordirs; Name: "{app}\app\backend\__pycache__"

[Code]
var
  PrereqChecked: Boolean;

function RunPrereqCheck(): Boolean;
var
  ResultCode: Integer;
  ScriptPath: String;
begin
  ScriptPath := ExpandConstant('{tmp}\Check-Prerequisites.ps1');
  // Prerequisites live under {app}\app\windows\scripts at install time, but
  // during THIS check that directory may not exist yet (files haven't been
  // copied). Extract it to {tmp} instead so the check works before [Files]
  // has run, matching the check-before-you-commit-disk-space intent.
  ExtractTemporaryFile('Check-Prerequisites.ps1');
  Exec('powershell.exe',
    '-NoProfile -ExecutionPolicy Bypass -File "' + ScriptPath + '"',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Result := (ResultCode = 0);
end;

function InitializeSetup(): Boolean;
begin
  Result := True;
  // Real prerequisite enforcement happens on the wizard's own Ready-to-
  // Install step via NextButtonClick below (Inno Setup runs InitializeSetup
  // before any UI exists, too early to show a meaningful message box for a
  // failed check); this hook is kept as a placeholder for a future silent/
  // unattended pre-check without a UI, intentionally not implemented until
  // there's a real unattended install path to serve.
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if (CurPageID = wpReady) and (not PrereqChecked) then
  begin
    if not RunPrereqCheck() then
    begin
      if MsgBox('One or more required components (Docker Desktop, sufficient disk space, or Administrator privileges) were not detected. ' +
                'The platform will not run correctly without them.' + #13#10 + #13#10 +
                'Continue installing anyway?', mbConfirmation, MB_YESNO) = IDNO then
      begin
        Result := False;
        Exit;
      end;
    end;
    PrereqChecked := True;
  end;
end;

// Standalone modal "type DELETE to confirm" dialog. Inno Setup's
// InputQuery/CreateInputQueryPage helpers are wizard-page constructs tied to
// the normal Setup UI flow and are not usable from InitializeUninstall
// (there is no wizard page flow during an uninstall) -- so this builds a
// plain TSetupForm with an edit box and OK/Cancel buttons by hand.
function PromptTypeDeleteToConfirm(): Boolean;
var
  ConfirmForm: TSetupForm;
  Prompt: TNewStaticText;
  Edit: TNewEdit;
  OKButton, CancelButton: TNewButton;
begin
  Result := False;
  ConfirmForm := CreateCustomForm(ScaleX(420), ScaleY(160), False, False);
  try
    ConfirmForm.Caption := 'Remove Everything -- Confirm';
    ConfirmForm.Position := poScreenCenter;

    Prompt := TNewStaticText.Create(ConfirmForm);
    Prompt.Parent := ConfirmForm;
    Prompt.Left := ScaleX(8);
    Prompt.Top := ScaleY(8);
    Prompt.Width := ConfirmForm.ClientWidth - ScaleX(16);
    Prompt.Height := ScaleY(80);
    Prompt.AutoSize := False;
    Prompt.WordWrap := True;
    Prompt.Caption := 'This PERMANENTLY deletes all cases, investigations, watchlists, ' +
      'notes, the database, and all saved credentials -- there is no undo and no backup ' +
      'is taken automatically.' + #13#10 + #13#10 +
      'Type DELETE (all caps) below to confirm.';

    Edit := TNewEdit.Create(ConfirmForm);
    Edit.Parent := ConfirmForm;
    Edit.Left := ScaleX(8);
    Edit.Top := ScaleY(92);
    Edit.Width := ConfirmForm.ClientWidth - ScaleX(16);

    OKButton := TNewButton.Create(ConfirmForm);
    OKButton.Parent := ConfirmForm;
    OKButton.Left := ConfirmForm.ClientWidth - ScaleX(176);
    OKButton.Top := ScaleY(124);
    OKButton.Width := ScaleX(80);
    OKButton.Caption := 'OK';
    OKButton.ModalResult := mrOk;

    CancelButton := TNewButton.Create(ConfirmForm);
    CancelButton.Parent := ConfirmForm;
    CancelButton.Left := ConfirmForm.ClientWidth - ScaleX(88);
    CancelButton.Top := ScaleY(124);
    CancelButton.Width := ScaleX(80);
    CancelButton.Caption := 'Cancel';
    CancelButton.ModalResult := mrCancel;

    ConfirmForm.ActiveControl := Edit;
    Result := (ConfirmForm.ShowModal() = mrOk) and (Edit.Text = 'DELETE');
  finally
    ConfirmForm.Free();
  end;
end;

// --- Uninstall: Remove Application (keep data) vs Remove Everything ---
//
// "Remove Application" is the default and matches what [UninstallDelete]/
// Inno's own file removal already does: binaries under {app} go away,
// ProgramData (config\.env, logs, backups) is left alone so a reinstall or
// a future version can pick up the same configuration and credentials.
//
// "Remove Everything" is the explicit, destructive opt-in the master
// prompt requires: it also stops+removes the Docker containers AND volumes
// (deleting all case/investigation/watchlist data permanently) and deletes
// ProgramData. It requires typing DELETE to confirm, not just a Yes/No,
// since a misclick on Yes/No is exactly the kind of accident this project's
// two credential/data-loss permission denials earlier already flagged as
// unacceptable to risk casually.
function InitializeUninstall(): Boolean;
var
  ResultCode: Integer;
  RemoveEverything: Boolean;
  AppDir, DataDir: String;
begin
  Result := True;
  RemoveEverything := False;

  // A /VERYSILENT uninstall (scripted/unattended removal) has no one
  // present to answer a MsgBox -- confirmed live: without this check, a
  // silent uninstall hangs forever on the prompt below, since
  // /SUPPRESSMSGBOXES only silences Inno Setup's OWN built-in message
  // boxes, not custom ones created here. Default to the non-destructive
  // "keep data" path in that case; Remove Everything is a manual,
  // interactive-only choice specifically because it's irreversible.
  if UninstallSilent() then
  begin
    RemoveEverything := False;
  end
  else
  begin
    case MsgBox('Remove HORIZON GRID?' + #13#10 + #13#10 +
                'Choose Yes to remove the application but KEEP your configuration, ' +
                'credentials, and all investigation data (cases, watchlists, notes) -- ' +
                'reinstalling later will pick up right where you left off.' + #13#10 + #13#10 +
                'Choose No to choose a different removal option.',
                mbConfirmation, MB_YESNOCANCEL) of
      IDYES: RemoveEverything := False;
      IDNO:
        begin
          if not PromptTypeDeleteToConfirm() then
          begin
            Result := False;
            Exit;
          end;
          RemoveEverything := True;
        end;
      IDCANCEL:
        begin
          Result := False;
          Exit;
        end;
    end;
  end;

  AppDir := ExpandConstant('{app}');
  // Literal on-disk ProgramData folder name -- intentionally NOT
  // {#MyAppFolderName}/{#MyAppName}: this must keep resolving to the real
  // existing install's data directory regardless of any rebrand define
  // above. Left as a hardcoded string exactly like Common.ps1's own
  // $script:DataDir, on purpose -- see this file's own header comment.
  DataDir := ExpandConstant('{commonappdata}\IOC Intelligence Platform');

  if RemoveEverything then
  begin
    // -v removes the named volumes (postgres_data, neo4j_data,
    // opensearch_data) -- this is the actual data-destroying step; without
    // -v, `down` alone would already have preserved everything, which is
    // exactly the "keep data" path and NOT what this branch is for.
    //
    // WorkingDir (4th Exec param) MUST be AppDir+'\app', not '' -- confirmed
    // live that Docker Compose derives its project name from the CURRENT
    // WORKING DIRECTORY's basename when no top-level `name:` is set in the
    // compose file (this project has none), completely independent of which
    // -f files are passed. An empty WorkingDir here left `down` running
    // against a phantom project matching wherever powershell.exe's own
    // process happened to default its cwd to -- not the real running
    // project (named "app", confirmed live via `docker compose ls`, from
    // {app}\app's own directory name) -- so it found zero matching
    // containers, exited 0, and silently left every real container running.
    // Every other script in this codebase avoids this by Push-Location-ing
    // into $AppRepoDir before calling docker compose (see Common.ps1's
    // Invoke-DockerCompose); this Exec call needs the equivalent.
    Exec('powershell.exe',
      '-NoProfile -ExecutionPolicy Bypass -Command "' +
      'docker compose -f ''' + AppDir + '\app\docker-compose.yml'' ' +
      '-f ''' + AppDir + '\app\docker-compose.prod.yml'' ' +
      '--env-file ''' + DataDir + '\config\.env'' down -v"',
      AppDir + '\app', SW_HIDE, ewWaitUntilTerminated, ResultCode);

    if DirExists(DataDir) then
      DelTree(DataDir, True, True, True);
  end
  else
  begin
    // Keep-data path: stop containers so nothing is left running after
    // uninstall, but do NOT pass -v -- volumes (and therefore all data)
    // survive for a future reinstall. Same WorkingDir fix as above.
    Exec('powershell.exe',
      '-NoProfile -ExecutionPolicy Bypass -Command "' +
      'docker compose -f ''' + AppDir + '\app\docker-compose.yml'' ' +
      '-f ''' + AppDir + '\app\docker-compose.prod.yml'' ' +
      '--env-file ''' + DataDir + '\config\.env'' down"',
      AppDir + '\app', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;

  // Firewall rule isn't user data -- remove it regardless of which branch
  // ran above (RemoveEverything or keep-data). Inlined as a plain -Command
  // rather than dot-sourcing Common.ps1's Remove-AppFirewallRule, matching
  // the two Exec calls above: Pascal Script's Exec launches a fresh process
  // per call, so it can't reuse functions from an already-running session
  // anyway.
  Exec('powershell.exe',
    '-NoProfile -ExecutionPolicy Bypass -Command "' +
    'Get-NetFirewallRule -DisplayName ''HORIZON GRID'' -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue"',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  // The boot-startup and health-watchdog Scheduled Tasks (Common.ps1's
  // Register-BootAndWatchdogTasks) aren't user data either -- remove them
  // unconditionally, same reasoning as the firewall rule above. Named
  // literally rather than reusing $script:AppDisplayName (Pascal Script has
  // no access to that PowerShell variable) -- must stay in sync with
  // Common.ps1's $script:StartupTaskName/$script:WatchdogTaskName/
  // $script:BackupTaskName if the display name ever changes.
  Exec('powershell.exe',
    '-NoProfile -ExecutionPolicy Bypass -Command "' +
    'Unregister-ScheduledTask -TaskName ''HORIZON GRID Startup'' -Confirm:$false -ErrorAction SilentlyContinue; ' +
    'Unregister-ScheduledTask -TaskName ''HORIZON GRID Watchdog'' -Confirm:$false -ErrorAction SilentlyContinue; ' +
    'Unregister-ScheduledTask -TaskName ''HORIZON GRID Daily Backup'' -Confirm:$false -ErrorAction SilentlyContinue"',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  // {app}\app\.env (Sync-ComposeEnvFile's mirror of the real config, kept
  // there because docker-compose.yml's env_file: .env directive resolves
  // relative to the compose project directory -- see Common.ps1's own
  // comment for the full story) is locked to Administrators+SYSTEM via
  // icacls, same as the ProgramData original. Confirmed live that Inno
  // Setup's own uninstall file-removal (driven by the [Files] manifest)
  // could NOT delete it even though this uninstaller prompted for and
  // received UAC elevation -- it silently left the file and therefore the
  // whole {app} directory behind, so "Uninstall" appeared to succeed but
  // Program Files\IOC Intelligence Platform never actually went away.
  // Strip the custom ACL back to something Inno's own cleanup can remove,
  // from here, where InitializeUninstall's Exec calls are already
  // confirmed to run with real elevated rights.
  if FileExists(AppDir + '\app\.env') then
  begin
    Exec('icacls.exe', '"' + AppDir + '\app\.env" /reset', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    DeleteFile(AppDir + '\app\.env');
  end;
end;
