<#
.SYNOPSIS
    Writes the platform's .env file from a settings hashtable built by the
    setup wizard. This is the ONLY place that constructs .env, so the wizard
    GUI never string-concatenates secrets into a file directly.

.DESCRIPTION
    $Settings keys map 1:1 to the variables docker-compose.yml and
    backend/.env.example already expect -- see .env.example at the repo
    root for the authoritative list this mirrors. Unset optional keys are
    written as empty (matching .env.example's own convention) rather than
    omitted, so re-running the wizard later to add a key is a pure
    find-and-replace, not a line-insertion.
#>
function ConvertTo-SafeEnvValue {
    <#
    .SYNOPSIS
        Makes a credential/setting value safe to write as a raw KEY=value
        line in a .env file, consumed both by Docker Compose's own env_file
        parser and by the backend's pydantic-settings loader.

    .DESCRIPTION
        Found during the API-configuration investigation: Write-PlatformEnvFile
        previously interpolated every value directly into a line with zero
        escaping. Two concrete failure modes follow directly from that:
          - A value containing a literal '#' truncates silently at that
            point -- '#' starts a comment in .env format -- so the stored
            credential becomes a different (broken) string with no error
            anywhere in the pipeline.
          - A value containing a CR/LF (e.g. a trailing newline from a
            clipboard paste, which is a common real copy-paste artifact for
            API keys/tokens) splits into multiple lines, corrupting every
            line after it in the file.
        Newlines are stripped outright (a key can never legitimately need
        one). A value containing '#' is rejected with a clear, specific
        error instead of being silently corrupted, since safely quoting it
        would depend on both consumers' quoting support agreeing exactly,
        which was not verified for the Compose parser specifically.
    #>
    param([string]$Value, [string]$FieldNameForError)

    if ([string]::IsNullOrEmpty($Value)) { return $Value }

    $stripped = $Value -replace "`r", "" -replace "`n", ""
    if ($stripped -match "#") {
        throw "The value entered for '$FieldNameForError' contains a '#' character, which cannot be safely stored in the configuration file (it would be silently truncated there). Please check for a copy-paste error and remove it, then save again."
    }
    return $stripped
}

function Write-PlatformEnvFile {
    param(
        [Parameter(Mandatory)][hashtable]$Settings,
        [Parameter(Mandatory)][string]$Path
    )

    # Every credential/setting value that ends up in the file passes through
    # ConvertTo-SafeEnvValue first -- one central choke point protects every
    # field written below rather than requiring each caller to remember to
    # sanitize its own inputs (the same "fix the shared abstraction, not a
    # one-off patch" principle applied throughout this fix).
    $safe = @{}
    foreach ($key in $Settings.Keys) {
        $safe[$key] = ConvertTo-SafeEnvValue -Value $Settings[$key] -FieldNameForError $key
    }
    $Settings = $safe

    $lines = @(
        "# Generated by the HORIZON GRID Windows setup wizard."
        "# Do not commit this file -- it contains real credentials."
        "# Re-run the setup wizard (Start Menu -> IOC Intelligence Platform -> Configuration)"
        "# to change any of these values later."
        ""
        "# --- Security ---"
        "JWT_SECRET_KEY=$($Settings.JwtSecretKey)"
        ""
        "# --- Host port mapping (changed here if the installer detected a conflict) ---"
        "HOST_PORT_FRONTEND=$($Settings.PortFrontend)"
        "HOST_PORT_BACKEND=$($Settings.PortBackend)"
        "HOST_PORT_POSTGRES=$($Settings.PortPostgres)"
        "HOST_PORT_REDIS=$($Settings.PortRedis)"
        "HOST_PORT_NEO4J_HTTP=$($Settings.PortNeo4jHttp)"
        "HOST_PORT_NEO4J_BOLT=$($Settings.PortNeo4jBolt)"
        "HOST_PORT_OPENSEARCH=$($Settings.PortOpenSearch)"
        "# Left empty by default -- the frontend auto-detects its own origin"
        "# (frontend/lib/api.ts's getApiUrl()) so this only needs a value for a"
        "# reverse-proxy or other non-default setup."
        "PUBLIC_API_URL=$($Settings.PublicApiUrl)"
        "# Best-effort LAN IP detected by the wizard (Common.ps1's"
        "# Get-LanIpAddress), for the Network Access panel's display only --"
        "# re-run Configuration if your network changes."
        "DETECTED_LAN_IP=$($Settings.DetectedLanIp)"
        ""
        "# --- Datastore credentials (randomly generated at install time) ---"
        "POSTGRES_USER=ioc"
        "POSTGRES_PASSWORD=$($Settings.PostgresPassword)"
        "POSTGRES_DB=ioc_intel"
        "NEO4J_PASSWORD=$($Settings.Neo4jPassword)"
        ""
        "# --- AI backend ---"
        "AI_BACKEND=$($Settings.AiBackend)"
        "OLLAMA_BASE_URL=$($Settings.OllamaBaseUrl)"
        "OLLAMA_MODEL=$($Settings.OllamaModel)"
        "BEDROCK_API_KEY=$($Settings.BedrockApiKey)"
        "AWS_ACCESS_KEY_ID=$($Settings.AwsAccessKeyId)"
        "AWS_SECRET_ACCESS_KEY=$($Settings.AwsSecretAccessKey)"
        "AWS_REGION=$($Settings.AwsRegion)"
        "BEDROCK_MODEL_ID=$($Settings.BedrockModelId)"
        "GEMINI_API_KEY=$($Settings.GeminiApiKey)"
        "GEMINI_MODEL_ID=$($Settings.GeminiModelId)"
        "ANTHROPIC_API_KEY=$($Settings.AnthropicApiKey)"
        "ANTHROPIC_MODEL_ID=$($Settings.AnthropicModelId)"
        "GROQ_API_KEY=$($Settings.GroqApiKey)"
        "GROQ_MODEL_ID=$($Settings.GroqModelId)"
        "OPENAI_API_KEY=$($Settings.OpenAiApiKey)"
        "OPENAI_MODEL_ID=$($Settings.OpenAiModelId)"
        "KIMI_API_KEY=$($Settings.KimiApiKey)"
        "KIMI_MODEL_ID=$($Settings.KimiModelId)"
        "DEEPSEEK_API_KEY=$($Settings.DeepSeekApiKey)"
        "DEEPSEEK_MODEL_ID=$($Settings.DeepSeekModelId)"
        "XAI_API_KEY=$($Settings.XaiApiKey)"
        "XAI_MODEL_ID=$($Settings.XaiModelId)"
        "MISTRAL_API_KEY=$($Settings.MistralApiKey)"
        "MISTRAL_MODEL_ID=$($Settings.MistralModelId)"
        "OPENROUTER_API_KEY=$($Settings.OpenRouterApiKey)"
        "OPENROUTER_MODEL_ID=$($Settings.OpenRouterModelId)"
        ""
        "# --- Free-tier intelligence providers ---"
        "VIRUSTOTAL_API_KEY=$($Settings.VirusTotalApiKey)"
        "ABUSEIPDB_API_KEY=$($Settings.AbuseIpdbApiKey)"
        "OTX_API_KEY=$($Settings.OtxApiKey)"
        "NVD_API_KEY=$($Settings.NvdApiKey)"
        "ABUSECH_AUTH_KEY=$($Settings.AbuseChAuthKey)"
        ""
        "# --- Paid / optional intelligence providers ---"
        "HYBRID_ANALYSIS_API_KEY=$($Settings.HybridAnalysisApiKey)"
        "CENSYS_PERSONAL_ACCESS_TOKEN=$($Settings.CensysPersonalAccessToken)"
        "CENSYS_ORGANIZATION_ID=$($Settings.CensysOrganizationId)"
        "PHISHTANK_API_KEY=$($Settings.PhishTankApiKey)"
        ""
    )

    $dir = Split-Path $Path
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    [System.IO.File]::WriteAllLines($Path, $lines, [System.Text.UTF8Encoding]::new($false))

    # .env now contains real secrets on disk -- restrict to Administrators +
    # SYSTEM immediately, before returning control to any caller.
    $null = & icacls.exe $Path /inheritance:r /grant:r "*S-1-5-32-544:F" "*S-1-5-18:F" 2>&1
}

function New-DefaultPlatformSettings {
    <# Returns a hashtable pre-populated with generated secrets and default
       ports/models, for the wizard to layer user input on top of. Keeping
       this separate from Write-PlatformEnvFile means the wizard can inspect/
       edit values before anything touches disk. #>
    return @{
        JwtSecretKey             = New-RandomSecret -Bytes 48
        PostgresPassword         = New-RandomSecret -Bytes 24
        Neo4jPassword            = New-RandomSecret -Bytes 24

        PortFrontend             = 3000
        PortBackend              = 8000
        PortPostgres             = 5433
        PortRedis                = 6379
        PortNeo4jHttp            = 7475
        PortNeo4jBolt            = 7688
        PortOpenSearch           = 9200

        PublicApiUrl             = ""
        DetectedLanIp            = ""

        AiBackend                = "ollama"
        OllamaBaseUrl            = "http://host.docker.internal:11434"
        OllamaModel              = "llama3.2:3b"
        BedrockApiKey            = ""
        AwsAccessKeyId           = ""
        AwsSecretAccessKey       = ""
        AwsRegion                = "us-east-1"
        BedrockModelId           = "anthropic.claude-sonnet-4-5-20250929-v1:0"
        GeminiApiKey             = ""
        GeminiModelId            = "gemini-2.0-flash"
        AnthropicApiKey          = ""
        AnthropicModelId         = "claude-sonnet-4-5-20250929"
        GroqApiKey               = ""
        GroqModelId              = "llama-3.3-70b-versatile"
        OpenAiApiKey             = ""
        OpenAiModelId            = "gpt-4o-mini"
        KimiApiKey               = ""
        KimiModelId              = "kimi-k2.5"
        DeepSeekApiKey           = ""
        DeepSeekModelId          = "deepseek-v4-flash"
        XaiApiKey                = ""
        XaiModelId               = "grok-4.6"
        MistralApiKey            = ""
        MistralModelId           = "mistral-small-2506"
        OpenRouterApiKey         = ""
        OpenRouterModelId        = "openai/gpt-4o"

        VirusTotalApiKey         = ""
        AbuseIpdbApiKey          = ""
        OtxApiKey                = ""
        NvdApiKey                = ""
        AbuseChAuthKey           = ""
        HybridAnalysisApiKey     = ""
        CensysPersonalAccessToken = ""
        CensysOrganizationId     = ""
        PhishTankApiKey          = ""
    }
}
