#!/usr/bin/env python3
"""Regression tests for ENCRYPTION_MASTER_KEY handling in setup_wizard.py.

Bug: neither the fresh-install defaults, the existing-.env loader used on a
"sudo horizon-grid configure" re-run, nor the .env writer ever knew about
ENCRYPTION_MASTER_KEY. Concretely, on a reconfigure:

    settings = default_settings()          # always generates a NEW random
                                            # EncryptionMasterKey in memory
    if is_upgrade:
        settings.update(load_existing_env(path))  # ENCRYPTION_MASTER_KEY was
                                                    # not in ENV_KEY_TO_SETTINGS_KEY,
                                                    # so the real on-disk value
                                                    # was never loaded back over
                                                    # that fresh default
    write_platform_env_file(settings, path)        # ENCRYPTION_MASTER_KEY was
                                                    # not in the fixed lines
                                                    # list, so it never made it
                                                    # to disk either

The net effect: every reconfigure silently dropped (pre-fix: not written at
all) whatever key had actually been used to encrypt existing provider/AI
credentials (app/core/crypto.py), permanently orphaning them -- and even a
fresh install never got a real ENCRYPTION_MASTER_KEY at all, defeating the
whole point of having it be independent from JWT_SECRET_KEY.

No existing pytest/docker wiring exists for this standalone script (see
test_host_gateway_detection.py's own note), so this follows the same
convention: a dependency-free unittest module living next to the script,
run directly via:

    python3 linux/wizard/test_encryption_master_key.py
"""
import base64
import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import setup_wizard  # noqa: E402


class EncryptionMasterKeyDefaultsTests(unittest.TestCase):
    def test_default_settings_includes_a_valid_fernet_key(self):
        settings = setup_wizard.default_settings()
        self.assertIn("EncryptionMasterKey", settings)
        key = settings["EncryptionMasterKey"]
        self.assertTrue(key, "a fresh install must get a real generated key, not an empty one")
        # Must decode to exactly 32 raw bytes -- Fernet()'s own hard
        # requirement (backend/app/core/crypto.py's _fernet() passes this
        # value straight into Fernet() with no derivation step).
        decoded = base64.urlsafe_b64decode(key.encode("ascii"))
        self.assertEqual(len(decoded), 32)

    def test_default_settings_generates_a_different_key_each_call(self):
        first = setup_wizard.default_settings()["EncryptionMasterKey"]
        second = setup_wizard.default_settings()["EncryptionMasterKey"]
        self.assertNotEqual(first, second)


class EncryptionMasterKeyPreservedAcrossReconfigureTests(unittest.TestCase):
    """Reproduces the exact reported scenario: an administrator hand-adds
    ENCRYPTION_MASTER_KEY to .env, then reconfigures for something unrelated
    (here: a new AI backend). That value must survive verbatim."""

    def setUp(self):
        self.tmpdir = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmpdir.cleanup)
        self.env_path = os.path.join(self.tmpdir.name, ".env")

    def test_hand_added_key_survives_a_reconfigure_write(self):
        hand_added_key = "kQ8f3z2vN0mYb1cWq7sT4uJhR6pL9xVaZdE5oGiC0AA="
        with open(self.env_path, "w", encoding="utf-8") as f:
            f.write(
                "JWT_SECRET_KEY=original-jwt-secret\n"
                "ENCRYPTION_MASTER_KEY=%s\n"
                "AI_BACKEND=ollama\n" % hand_added_key
            )

        # Exactly what Wizard.__init__ does on a reconfigure run.
        settings = setup_wizard.default_settings()
        settings.update(setup_wizard.load_existing_env(self.env_path))

        # The real on-disk key must have been loaded back, not left at the
        # fresh in-memory default generated by default_settings().
        self.assertEqual(settings["EncryptionMasterKey"], hand_added_key)

        # Simulate reconfiguring something unrelated, then re-writing .env,
        # exactly like a real "sudo horizon-grid configure" run for a new
        # AI backend would.
        settings["AiBackend"] = "anthropic"
        setup_wizard.write_platform_env_file(settings, self.env_path)

        with open(self.env_path, "r", encoding="utf-8") as f:
            written = f.read()
        self.assertIn(
            "ENCRYPTION_MASTER_KEY=%s" % hand_added_key,
            written,
            "reconfiguring an unrelated setting must never drop or rotate "
            "an administrator's existing ENCRYPTION_MASTER_KEY",
        )

    def test_fresh_install_writes_the_generated_key_to_disk(self):
        settings = setup_wizard.default_settings()
        setup_wizard.write_platform_env_file(settings, self.env_path)

        with open(self.env_path, "r", encoding="utf-8") as f:
            written = f.read()
        self.assertIn("ENCRYPTION_MASTER_KEY=%s" % settings["EncryptionMasterKey"], written)


if __name__ == "__main__":
    unittest.main()
