"use client";

import * as Tabs from "@radix-ui/react-tabs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cn, riskScoreColor, verdictColor } from "@/lib/utils";
import type { FinalAssessment, RiskAssessment } from "@/lib/types";

export interface FinalAssessmentPanelProps {
  assessment: FinalAssessment | null;
}

const TAB_TRIGGER_CLASS = cn(
  "rounded-md px-3 py-1.5 text-sm font-medium text-muted-foreground transition-colors",
  "hover:text-foreground",
  "data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
);

function formatVerdict(verdict: string): string {
  return verdict.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function Prose({ children }: { children: string }) {
  return <p className="whitespace-pre-wrap text-sm leading-relaxed text-foreground">{children}</p>;
}

function Pill({ label, tone }: { label: string; tone: "success" | "warning" }) {
  const toneClass =
    tone === "success"
      ? "border-success/30 bg-success/10 text-success"
      : "border-warning/30 bg-warning/10 text-warning";
  return (
    <span className={cn("inline-flex items-center rounded-full border px-3 py-1 text-xs font-medium", toneClass)}>
      {label}
    </span>
  );
}

function StatTile({ label, value, valueClassName }: { label: string; value: string; valueClassName?: string }) {
  return (
    <div className="flex flex-col gap-1 rounded-lg border border-border bg-muted/30 p-3">
      <span className="text-xs text-muted-foreground">{label}</span>
      <span className={cn("text-xl font-semibold tabular-nums", valueClassName)}>{value}</span>
    </div>
  );
}

function RiskStatGrid({ risk }: { risk: RiskAssessment }) {
  return (
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
      <StatTile
        label="Overall risk score"
        value={risk.overall_risk_score.toFixed(0)}
        valueClassName={riskScoreColor(risk.overall_risk_score)}
      />
      <StatTile
        label="Confidence score"
        value={risk.confidence_score.toFixed(0)}
        valueClassName="text-foreground"
      />
      <StatTile label="Severity" value={risk.severity} valueClassName={verdictColor(risk.severity)} />
      <StatTile label="Reputation" value={risk.reputation} valueClassName="text-foreground" />
      <StatTile
        label="Malicious probability"
        value={`${risk.malicious_probability.toFixed(0)}%`}
        valueClassName={riskScoreColor(risk.malicious_probability)}
      />
      <StatTile label="Analyst confidence" value={risk.analyst_confidence} valueClassName="text-foreground" />
    </div>
  );
}

function PendingPlaceholder() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Final Assessment</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="flex flex-col items-center justify-center gap-3 py-10 text-center">
          <div className="h-8 w-8 animate-pulse rounded-full bg-primary/40" />
          <p className="animate-pulse text-sm text-muted-foreground">
            Final assessment pending -- waiting for all providers to finish
          </p>
          <div className="mt-2 flex w-full max-w-md flex-col gap-2">
            <div className="h-3 w-full animate-pulse rounded bg-muted" />
            <div className="h-3 w-5/6 animate-pulse rounded bg-muted" />
            <div className="h-3 w-2/3 animate-pulse rounded bg-muted" />
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

export function FinalAssessmentPanel({ assessment }: FinalAssessmentPanelProps) {
  if (!assessment) {
    return <PendingPlaceholder />;
  }

  const final = assessment;

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between gap-2">
        <CardTitle>Final Assessment</CardTitle>
        {final.ai_backend ? (
          <span
            className="rounded-full border border-border bg-muted/40 px-2.5 py-1 text-[11px] text-muted-foreground"
            title="Which AI backend and model actually produced this conclusion"
          >
            Generated by <span className="font-medium text-foreground capitalize">{final.ai_backend}</span>
            {final.ai_model ? <> &middot; <span className="font-mono">{final.ai_model}</span></> : null}
          </span>
        ) : final.ai_outcome === "failed" ? (
          // Real gap fixed: this used to render identically to the
          // no-evidence skip below (both just check ai_backend's
          // truthiness, and a genuine failure never sets ai_backend
          // either) -- an operator had no way to tell "correctly decided
          // there was nothing to assess" apart from "the AI backend was
          // down/errored and this text below is a fallback, not a real
          // conclusion." Distinguishing PROVIDER FAILURE from NO AI RESULT
          // is a real requirement, not cosmetic.
          <span
            className="rounded-full border border-destructive/30 bg-destructive/10 px-2.5 py-1 text-[11px] font-medium text-destructive"
            title="The AI backend was called but generation failed -- the text below is a fallback, not a real AI-produced conclusion. Check server logs / AI Providers page."
          >
            AI generation failed
          </span>
        ) : (
          <span
            className="rounded-full border border-border bg-muted/40 px-2.5 py-1 text-[11px] text-muted-foreground"
            title="No AI backend was called -- there was no provider evidence to assess"
          >
            No AI call (no evidence to assess)
          </span>
        )}
      </CardHeader>
      <CardContent>
        <Tabs.Root defaultValue="executive">
          <Tabs.List className="mb-4 flex flex-wrap gap-1 border-b border-border pb-2">
            <Tabs.Trigger value="executive" className={TAB_TRIGGER_CLASS}>
              Executive Summary
            </Tabs.Trigger>
            <Tabs.Trigger value="technical" className={TAB_TRIGGER_CLASS}>
              Technical Summary
            </Tabs.Trigger>
            <Tabs.Trigger value="threat" className={TAB_TRIGGER_CLASS}>
              Threat Assessment
            </Tabs.Trigger>
            <Tabs.Trigger value="relationships" className={TAB_TRIGGER_CLASS}>
              Relationships
            </Tabs.Trigger>
            <Tabs.Trigger value="risk" className={TAB_TRIGGER_CLASS}>
              Risk &amp; Verdict
            </Tabs.Trigger>
          </Tabs.List>

          <Tabs.Content value="executive" className="flex flex-col gap-4">
            <Prose>{final.executive_summary}</Prose>
            <div className="flex flex-col gap-2 rounded-lg border border-border bg-muted/30 p-4">
              <span
                className={cn(
                  "inline-flex w-fit items-center rounded-md border-2 border-current bg-muted/40 px-3 py-1.5 text-lg font-bold",
                  verdictColor(final.final_verdict)
                )}
              >
                {formatVerdict(final.final_verdict)}
              </span>
              <p className="text-sm text-muted-foreground">{final.verdict_rationale}</p>
            </div>
          </Tabs.Content>

          <Tabs.Content value="technical" className="flex flex-col gap-4">
            <Prose>{final.technical_summary}</Prose>
          </Tabs.Content>

          <Tabs.Content value="threat" className="flex flex-col gap-4">
            <Prose>{final.threat_assessment}</Prose>

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div className="flex flex-col gap-2">
                <span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                  Agreeing providers
                </span>
                <div className="flex flex-wrap gap-2">
                  {final.agreeing_providers.length === 0 ? (
                    <span className="text-xs text-muted-foreground">None</span>
                  ) : (
                    final.agreeing_providers.map((provider) => (
                      <Pill key={provider} label={provider} tone="success" />
                    ))
                  )}
                </div>
              </div>
              <div className="flex flex-col gap-2">
                <span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                  Disagreeing providers
                </span>
                <div className="flex flex-wrap gap-2">
                  {final.disagreeing_providers.length === 0 ? (
                    <span className="text-xs text-muted-foreground">None</span>
                  ) : (
                    final.disagreeing_providers.map((provider) => (
                      <Pill key={provider} label={provider} tone="warning" />
                    ))
                  )}
                </div>
              </div>
            </div>

            <div className="flex flex-col gap-2">
              <span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Supporting evidence
              </span>
              {final.supporting_evidence.length === 0 ? (
                <span className="text-xs text-muted-foreground">No supporting evidence provided</span>
              ) : (
                <ol className="flex flex-col gap-2 pl-5 text-sm text-foreground">
                  {final.supporting_evidence.map((item, idx) => (
                    <li key={idx} className="list-decimal leading-relaxed">
                      {item}
                    </li>
                  ))}
                </ol>
              )}
            </div>
          </Tabs.Content>

          <Tabs.Content value="relationships" className="flex flex-col gap-4">
            <Prose>{final.relationships_summary}</Prose>
          </Tabs.Content>

          <Tabs.Content value="risk" className="flex flex-col gap-4">
            <RiskStatGrid risk={final.risk} />
          </Tabs.Content>
        </Tabs.Root>
      </CardContent>
    </Card>
  );
}
