"""add final assessment records

Revision ID: 2652d888a33f
Revises: 0f2dc283823e
Create Date: 2026-08-12 13:04:39.794393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2652d888a33f'
down_revision: Union[str, None] = '0f2dc283823e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_assessment_records',
    sa.Column('lookup_id', sa.UUID(), nullable=False),
    sa.Column('ai_backend', sa.String(length=64), nullable=False),
    sa.Column('ai_model', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lookup_id'], ['ioc_lookups.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_assessment_records_lookup_id'), 'final_assessment_records', ['lookup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_final_assessment_records_lookup_id'), table_name='final_assessment_records')
    op.drop_table('final_assessment_records')
    # ### end Alembic commands ###
