"""initial schema

Revision ID: 660d2aa3bc20
Revises: 
Create Date: 2026-08-07 08:50:27.166750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '660d2aa3bc20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ioc_lookups',
    sa.Column('ioc_value', sa.String(length=2048), nullable=False),
    sa.Column('ioc_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='lookupstatus'), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('final_verdict', sa.Enum('HIGHLY_MALICIOUS', 'MALICIOUS', 'SUSPICIOUS', 'UNKNOWN', 'LIKELY_BENIGN', 'BENIGN', 'SCANNER', 'TOR_EXIT_NODE', 'VPN', 'CDN', 'CLOUD_INFRASTRUCTURE', 'DORMANT_INFRASTRUCTURE', name='verdict'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('final_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ioc_lookups_ioc_type'), 'ioc_lookups', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_ioc_lookups_ioc_value'), 'ioc_lookups', ['ioc_value'], unique=False)
    op.create_table('ai_summaries',
    sa.Column('lookup_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lookup_id'], ['ioc_lookups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_summaries_lookup_id'), 'ai_summaries', ['lookup_id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_provider_id'), 'ai_summaries', ['provider_id'], unique=False)
    op.create_table('correlation_edges',
    sa.Column('lookup_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_value', sa.String(length=2048), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_value', sa.String(length=2048), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lookup_id'], ['ioc_lookups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_edges_lookup_id'), 'correlation_edges', ['lookup_id'], unique=False)
    op.create_table('provider_results',
    sa.Column('lookup_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lookup_id'], ['ioc_lookups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_results_lookup_id'), 'provider_results', ['lookup_id'], unique=False)
    op.create_index(op.f('ix_provider_results_provider_id'), 'provider_results', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_results_provider_id'), table_name='provider_results')
    op.drop_index(op.f('ix_provider_results_lookup_id'), table_name='provider_results')
    op.drop_table('provider_results')
    op.drop_index(op.f('ix_correlation_edges_lookup_id'), table_name='correlation_edges')
    op.drop_table('correlation_edges')
    op.drop_index(op.f('ix_ai_summaries_provider_id'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_lookup_id'), table_name='ai_summaries')
    op.drop_table('ai_summaries')
    op.drop_index(op.f('ix_ioc_lookups_ioc_value'), table_name='ioc_lookups')
    op.drop_index(op.f('ix_ioc_lookups_ioc_type'), table_name='ioc_lookups')
    op.drop_table('ioc_lookups')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
