"""add evidence, basket, and case management models

Revision ID: a6d3ad2bb63c
Revises: 660d2aa3bc20
Create Date: 2026-08-08 17:48:42.675067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a6d3ad2bb63c'
down_revision: Union[str, None] = '660d2aa3bc20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('analyst_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='caseseverity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'CONTAINED', 'RESOLVED', 'FALSE_POSITIVE', 'CLOSED', name='casestatus'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_analyst_id'), 'cases', ['analyst_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('basket_items',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('ioc_value', sa.String(length=2048), nullable=False),
    sa.Column('ioc_type', sa.String(length=64), nullable=False),
    sa.Column('latest_lookup_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['latest_lookup_id'], ['ioc_lookups.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'ioc_value', name='uq_basket_owner_ioc')
    )
    op.create_index(op.f('ix_basket_items_owner_id'), 'basket_items', ['owner_id'], unique=False)
    op.create_table('case_iocs',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('ioc_value', sa.String(length=2048), nullable=False),
    sa.Column('ioc_type', sa.String(length=64), nullable=False),
    sa.Column('lookup_id', sa.UUID(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['lookup_id'], ['ioc_lookups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_iocs_case_id'), 'case_iocs', ['case_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('anchor_type', sa.String(length=64), nullable=True),
    sa.Column('anchor_ref', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_table('case_reports',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_reports_case_id'), 'case_reports', ['case_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('lookup_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Enum('DETECTION', 'REPUTATION', 'RELATIONSHIP', 'MALWARE_ASSOCIATION', 'THREAT_ACTOR_ASSOCIATION', 'CAMPAIGN_ASSOCIATION', 'MITRE_TECHNIQUE', 'INFRASTRUCTURE', 'OTHER', name='evidencetype'), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('related_ioc_type', sa.String(length=64), nullable=True),
    sa.Column('related_ioc_value', sa.String(length=2048), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('observed_at', sa.String(length=64), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lookup_id'], ['ioc_lookups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_evidence_type'), 'evidence_items', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_items_lookup_id'), 'evidence_items', ['lookup_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_provider_id'), 'evidence_items', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_items_provider_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_lookup_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_evidence_type'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_case_reports_case_id'), table_name='case_reports')
    op.drop_table('case_reports')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_case_iocs_case_id'), table_name='case_iocs')
    op.drop_table('case_iocs')
    op.drop_index(op.f('ix_basket_items_owner_id'), table_name='basket_items')
    op.drop_table('basket_items')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_analyst_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
